### Runs builds on the commits you push after you’ve added a .travis.yml file.##
#before_install:
#  - sudo apt-get update
#  - sudo apt-get -y install libxml2-dev

language: node_js

# Установить версию Node.js
node_js:
  - '10.15.3'
cache: npm
    
#services:
  # Использовать командную строку Docker
#  - docker

install:
  - npm ci
  # Установить зависимости для тестов
  # - npm ci

#before_script:
  # Запустить сервер и клиент для тестов
#  - npm run dev &

script:
  # Запустить тесты
  - npm test
#  - npm run lint:fix


#lavguage: JavaScript
#language: java

### Configuring email notifications ###

#notifications:
#  email:
#    recipients:
#      - one@example.com
#      - other@example.com
#    on_success: never # default: change
#    on_failure: always # default: always



### Travis CI can deploy your static files to GitHub Pages after a successful build.###

#deploy:
#  provider: pages
#  skip_cleanup: true
#  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
#  keep_history: true
#  on:
#    branch: master
